import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components/Providers";
import Header from "@/components/layout/Header";

export const metadata: Metadata = {
  title: "Noesis Forge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <Providers attribute="class" defaultTheme="system" enableSystem>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
