services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=postgres
      - MINIO_ENDPOINT=minio:9000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - minio
      - minio-init
    networks:
      - noesis-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Web App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
      - INTERNAL_API_URL=http://backend:8000/api/v1
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - noesis-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: noesis_forge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1997
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - noesis-network

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    env_file:
      - ./backend/.env
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_DEFAULT_BUCKETS: noesis-documents
    ports:
      - "9000:9000"   # MinIO API
      - "9001:9001"   # MinIO Console (Web UI)
    volumes:
      - minio_data:/data
    networks:
      - noesis-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # MinIO Client for bucket creation
  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    env_file:
      - ./backend/.env
    networks:
      - noesis-network
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO to start...';
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      /usr/bin/mc mb myminio/noesis-documents --ignore-existing;
      /usr/bin/mc policy set public myminio/noesis-documents;
      echo 'MinIO bucket setup complete';
      "

volumes:
  postgres_data:
  minio_data:

networks:
  noesis-network:
    driver: bridge